- AI_relay/ValidImages.py
- AI_relay/train.py
- AI_relay/videoValid.py
yolo11을 이용한 커스텀 데이터셋 학습 및 바운딩 박스를 그려 성능 테스트
> [Feat] 모델 학습 및 검증

- Profanity_Filter/validate.py
레이블링이 되지 않은 데이터셋으로 예측을 실행하여 성능을 직접적으로 확인
> 레이블이 없는 test 데이터로 예측 실행 validation.py

- Profanity_Filter/quantization/dynamic_quantization.py
- Profanity_Filter/quantization/onnx_format.py
- Profanity_Filter/quantization/onnx_prediction.py
> [feat] 비속어 필터 onnx 양자화

- Profanity_Filter/validate.py
- gogo_ai_backend/predict_model.py
기존 상대 경로로 모델 로드 -> 허깅페이스에 올린 모델 로드
> [fix] 모델 로딩 방식 변경 (허깅페이스)

- gogo_ai_backend/.github/workflows/prod_cd.yml
- gogo_ai_backend/Dockerfile
GOGO 욕설 필터 배포용 도커 파일과 prod_cd 스크립트를 작성하였습니다.
> [Feat] 배포를 위한 도커 파일 및 스크립트 작성

- Profanity_Filter/quantization/dynamic_quantization.py
- Profanity_Filter/quantization/onnx_format.py
- Profanity_Filter/quantization/onnx_prediction.py
- Profanity_Filter/validate.py
- gogo_ai_backend/.github/workflows/prod_cd.yml
- gogo_ai_backend/Dockerfile
- gogo_ai_backend/predict_model.py
> v2025.04.08.1

- .github/workflows/stage_cd.yml
- gogo_ai_backend/config.py
- gogo_ai_backend/eureka.py
- gogo_ai_backend/pyproject.toml
- gogo_ai_backend/server.py
> [feat] 학교서버 배포용 cd 스크립트 추가

- gogo_ai_backend/event/consumer.py
- gogo_ai_backend/schema/filter.py
- gogo_ai_backend/test.py
변경된 이벤트 토픽에 맞춰 수정하였습니다
이벤트 토픽에 맞춰 filter.py 스펙 수정 및 consumer.py 수정 및 예측값이 비속어일 경우만 값을 보내도록 하였습니다..
> [fix] 변경된 이벤트 토픽에 맞춰 수정

- gogo_ai_backend/event/consumer.py
> [fix] schema 경로 수정

- .github/workflows/stage_cd.yml
stage-cd pull 경로 master->develop
stage-cd pull 경로는 develop이어야 하는데 master로 되어 있어 수정하였습니다.
> stage-cd pull 경로 master->develop

- gogo_ai_backend/event/consumer.py
> [fix] schema import 재수정

- .gitignore
- gogo_ai_backend/config.py
.env 관련 경로 설정을 변경하였습니다.
gitignore .env 파일 무시 설정 config.py env load 변경
> [fix] .env 경로 설정 변경

- .github/workflows/stage_cd.yml
서버내에 있는 env 파일을 사용하도록 docker run 부분을 수정하였습니다.
> [fix] 서버 내의 env 파일 사용 설정 

- .github/workflows/prod_cd.yml
prod 애플리케이션이 온프레미스 환경에 배포되게 수정하였습니다.
> [workflows] prod 애플리케이션 배포 설정 변경

- gogo_ai_backend/config.py
override 비활성화로 서버 내부 env 무시 해결
> [fix] overrride 비활성화 

- gogo_ai_backend/config.py
- gogo_ai_backend/event/consumer.py
- gogo_ai_backend/server.py
> [fix] 카프카 로깅 추가 및 쓸모 없는 환경변수 주석 처리

- gogo_ai_backend/config.py
- gogo_ai_backend/event/consumer.py
- gogo_ai_backend/server.py
> 2025.03.16.2

- gogo_ai_backend/eureka.py
> 2025.04.16.3

- gogo_ai_backend/config.py
- gogo_ai_backend/event/consumer.py
환경변수를 초기에 읽어온 환경변수를 고정해서 사용하지 않고 필요시 리로드하게 수정했습니다.
> [fix] 환경변수 초기고정 설정 수정

- gogo_ai_backend/server.py
> 2025.04.16.4

- AI_relay/datapreprocessing/Make_yoloYaml.py
- AI_relay/datapreprocessing/drawBoundingBox.py
- AI_relay/datapreprocessing/yoloFormat.py
데이터에서 공만 추출하였습니다
사람, 골대, 공 추출 -> 공만 추출
> [fix] 공만 인식하도록 전처리
